# Generated by Django 5.1.4 on 2025-01-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0004_osoba_data_dodania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='plec',
            field=models.IntegerField(choices=[(1, 'Kobieta'), (2, 'Męzczyzna'), (3, 'Inna')], default=3),
        ),
    ]
